# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('f_color', models.CharField(max_length=7)),
                ('f_animal', models.CharField(max_length=3)),
            ],
        ),
    ]
